---

data_filesystems:
  - path: /var/lib/awx/
    src: /dev/data_vg/lv_awx
  - path: /var/backups/automation-platform/
    src: /dev/data_vg/lv_backups_aap

data_logical_volumes:
  - name: lv_awx
    size: 60g
  - name: lv_backups_aap
    size: 60g
